/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-01-24 03:49:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class body_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 String sessionUsername = (String)session.getAttribute("username"); 
      out.write('\r');
      out.write('\n');
 String sessionType = (String)session.getAttribute("type"); 
      out.write("\r\n");
      out.write("<Body>\r\n");
      out.write("\r\n");
      out.write("<center><img src=\"./images/logo.jpg\"></center>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "table_start.jsp", out, true);
      out.write(' ');
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "table_title.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Control Bar", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("colspan", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("1", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("align", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("left", request.getCharacterEncoding()), out, true);
      out.write("\t\t\t\t\t\t\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "table_start_body.jsp", out, true);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "table_body.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("width", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("0", request.getCharacterEncoding()), out, true);
      out.write("\r\n");
      out.write("\t<table width=\"100%\" height=\"0\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"infobar\">\r\n");
      out.write("\t\t<tr> \r\n");
      out.write("\t\t\t<td width=\"50%\" height=\"0\" align=\"left\" valign=\"top\">\r\n");
      out.write("\t\t\t\t");
 if(sessionUsername != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"./index.jsp?page=profile\">Change Forum Profile</a>\r\n");
      out.write("\t\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<form action=\"servlet/forum.Login\" method=POST name=form>\r\n");
      out.write("\t\t\t\t\t\t\tUsername:<input type=\"text\" name=\"username\" size=\"10\" maxlength=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\tPassword:<input type=\"password\" name=\"password\" size=\"10\" maxlength=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"50%\" height=\"0\" align=\"right\" valign=\"top\">\r\n");
      out.write("\t\t\t\t");
 if(sessionUsername != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\tLogged in as: ");
      out.print( sessionUsername );
      out.write(" Type: ");
      out.print( sessionType );
      out.write("\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;[<a href=\"servlet/forum.Logout\">Logout</a>]\t\t\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "table_close_body.jsp", out, true);
      out.write("\t\t\t\t \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "table_close.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
