/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-01-24 04:34:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class textStyle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<table cellpadding=\"0\" cellspacing=\"5\" border=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("        \t<table id=\"tb37\" bgcolor=\"#304C77\" cellpadding=\"1\" cellspacing=\"0\" border=\"0\" >\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<table bgcolor=\"#ffffff\" cellpadding=\"6\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td nowrap align=\"center\"onmouseover=\"this.style.cursor='hand';this.style.backgroundColor='#FFFFFF';document.all.tb37.style.backgroundColor='#7E9FD0';\"onmouseout=\"this.style.backgroundColor='#ffffff';document.all.tb37.style.backgroundColor='#304C77';\" onclick=\"javascript:window.document.formmessage.message.value+='[B][/B]';window.document.formmessage.message.focus();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>B</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>\r\n");
      out.write("\t\t\t\t<table id=\"tb38\" bgcolor=\"#304C77\" cellpadding=\"1\" cellspacing=\"0\" border=\"0\" >\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table bgcolor=\"#ffffff\" cellpadding=\"6\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td nowrap align=\"center\"onmouseover=\"this.style.cursor='hand';this.style.backgroundColor='#FFFFFF';document.all.tb38.style.backgroundColor='#7E9FD0';\"onmouseout=\"this.style.backgroundColor='#ffffff';document.all.tb38.style.backgroundColor='#304C77';\" onclick=\"javascript:window.document.formmessage.message.value+='[I][/I]';window.document.formmessage.message.focus();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<b><i>i</i></b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>\r\n");
      out.write("\t\t\t\t<table id=\"tb39\" bgcolor=\"#304C77\" cellpadding=\"1\" cellspacing=\"0\" border=\"0\" >\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table bgcolor=\"#ffffff\" cellpadding=\"6\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td nowrap align=\"center\"onmouseover=\"this.style.cursor='hand';this.style.backgroundColor='#FFFFFF';document.all.tb39.style.backgroundColor='#7E9FD0';\"onmouseout=\"this.style.backgroundColor='#ffffff';document.all.tb39.style.backgroundColor='#304C77';\" onclick=\"javascript:window.document.formmessage.message.value+='[U][/U]';window.document.formmessage.message.focus();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<b><u>U</u></b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("            </td> \r\n");
      out.write("            <td>\r\n");
      out.write("\t\t\t\t<table id=\"tb40\" bgcolor=\"#304C77\" cellpadding=\"1\" cellspacing=\"0\" border=\"0\" >\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table bgcolor=\"#ffffff\" cellpadding=\"6\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td nowrap align=\"center\"onmouseover=\"this.style.cursor='hand';this.style.backgroundColor='#FFFFFF';document.all.tb40.style.backgroundColor='#7E9FD0';\"onmouseout=\"this.style.backgroundColor='#ffffff';document.all.tb40.style.backgroundColor='#304C77';\" onclick=\"javascript:window.document.formmessage.message.value+='[S][/S]';window.document.formmessage.message.focus();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<b><s>S</s></b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("            </td>\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t     <td>\r\n");
      out.write("\t\t\t\t<table id=\"tb41\" bgcolor=\"#304C77\" cellpadding=\"1\" cellspacing=\"0\" border=\"0\" >\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table bgcolor=\"#ffffff\" cellpadding=\"6\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td nowrap align=\"center\"onmouseover=\"this.style.cursor='hand';this.style.backgroundColor='#FFFFFF';document.all.tb41.style.backgroundColor='#7E9FD0';\"onmouseout=\"this.style.backgroundColor='#ffffff';document.all.tb41.style.backgroundColor='#304C77';\" onclick=\"javascript:window.document.formmessage.message.value+='[IMG][/IMG]';window.document.formmessage.message.focus();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<b>IMG</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("            </td>\r\n");
      out.write("\t\t     <td>\r\n");
      out.write("\t\t\t\t<table id=\"tb42\" bgcolor=\"#304C77\" cellpadding=\"1\" cellspacing=\"0\" border=\"0\" >\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table bgcolor=\"#ffffff\" cellpadding=\"6\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td nowrap align=\"center\"onmouseover=\"this.style.cursor='hand';this.style.backgroundColor='#FFFFFF';document.all.tb42.style.backgroundColor='#7E9FD0';\"onmouseout=\"this.style.backgroundColor='#ffffff';document.all.tb42.style.backgroundColor='#304C77';\" onclick=\"javascript:window.document.formmessage.message.value+='[URL=http://][/URL]';window.document.formmessage.message.focus();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<b>URL</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("            </td>\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("</table>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
