 drop table web_member;
 create table web_member
(
  ID                 VARCHAR2(64) not null,
  OID                VARCHAR2(32) default '',
  MEMNAME            VARCHAR2(100) default '',
  LOGINNAME          VARCHAR2(100) default '',
  PASSWD             VARCHAR2(100) default '',
  ISCHECK            NUMBER(1) default '0' not null,
  BANK_ACCOUNT_NAME  VARCHAR2(80) default '',
  BANK               VARCHAR2(80) default '',
  BANK_KHNAME        VARCHAR2(80) default '',
  BANK_ACCOUNT       VARCHAR2(80) default '',
  ANSWER             VARCHAR2(80) default '',
  ASKVALUE           VARCHAR2(80) default '',
  WITHDRAWALPASSWORD VARCHAR2(80) default '',
  WITHDRAWALNAME     VARCHAR2(80) default '',
  EMAIL              VARCHAR2(80) default '',
  PHONE              VARCHAR2(80) default '',
  SEX                NUMBER(1) default '0' not null,
  MONEY              NUMBER(10) default '0' not null,
  CREDIT             NUMBER(10) default '0' not null,
  ALIAS              VARCHAR2(200) default '',
  LOGDATE            TIMESTAMP(3) default to_timestamp('1900-01-01 00:00:00.00000', 'yyyy-mm-dd hh24:mi:ss:ff'),
  DOMAIN             VARCHAR2(200) default '',
  ADDDATE            TIMESTAMP(3) default to_timestamp('1900-01-01 00:00:00.00000', 'yyyy-mm-dd hh24:mi:ss:ff'),
  LANGUAGE           VARCHAR2(10) default '',
  ACTIVE             TIMESTAMP(3) default to_timestamp('1900-01-01 00:00:00.00000', 'yyyy-mm-dd hh24:mi:ss:ff'),
  LOGIP              VARCHAR2(32) default '',
  SETIP              VARCHAR2(32) default '',
  AGENTS             VARCHAR2(10) default '',
  CORPRATOR          VARCHAR2(10) default '',
  WORLD              VARCHAR2(10) default '',
  SUPER              VARCHAR2(10) default '',
  PAY_TYPE           NUMBER(1) default '0' not null,
  STATUS             NUMBER(1) default '1' not null,
  EDTVOU             NUMBER(1) default '0' not null,
  BETTYPE            NUMBER(1) default '0' not null,
  OPENTYPE           CHAR(1) default '',
  CURTYPE            VARCHAR2(10) default 'RMB' not null,
  FT_R_SCENE         NUMBER(10) default '2000' not null,
  FT_RE_SCENE        NUMBER(10) default '2000' not null,
  FT_ROU_SCENE       VARCHAR2(10) default '2000' not null,
  FT_M_SCENE         NUMBER(10) default '2000' not null,
  FT_OU_SCENE        NUMBER(10) default '2000' not null,
  FT_PD_SCENE        NUMBER(10) default '2000' not null,
  FT_T_SCENE         NUMBER(10) default '2000' not null,
  FT_EO_SCENE        NUMBER(10) default '2000' not null,
  FT_P_SCENE         NUMBER(10) default '2000' not null,
  FT_PR_SCENE        NUMBER(10) default '2000' not null,
  FT_F_SCENE         NUMBER(10) default '2000' not null,
  FT_M_BET           NUMBER(10) default '2000' not null,
  FT_R_BET           NUMBER(10) default '2000' not null,
  FT_OU_BET          NUMBER(10) default '2000' not null,
  FT_RE_BET          NUMBER(10) default '2000' not null,
  FT_ROU_BET         VARCHAR2(10) default '2000' not null,
  FT_T_BET           NUMBER(10) default '2000' not null,
  FT_EO_BET          NUMBER(10) default '2000' not null,
  FT_PD_BET          NUMBER(10) default '2000' not null,
  FT_F_BET           NUMBER(10) default '2000' not null,
  FT_P_BET           NUMBER(10) default '2000' not null,
  FT_PR_BET          NUMBER(10) default '2000' not null,
  FT_TURN_R          VARCHAR2(5) default '0' not null,
  FT_TURN_OU         VARCHAR2(5) default '0' not null,
  FT_TURN_M          VARCHAR2(5) default '0' not null,
  FT_TURN_RE         VARCHAR2(5) default '0' not null,
  FT_TURN_ROU        VARCHAR2(5) default '0' not null,
  FT_TURN_PD         VARCHAR2(5) default '0' not null,
  FT_TURN_T          VARCHAR2(5) default '0' not null,
  FT_TURN_EO         VARCHAR2(5) default '0' not null,
  FT_TURN_F          VARCHAR2(5) default '0' not null,
  FT_TURN_P          VARCHAR2(5) default '0' not null,
  FT_TURN_PR         VARCHAR2(5) default '0' not null,
  TN_R_BET           VARCHAR2(10) default '2000' not null,
  TN_RE_BET          VARCHAR2(10) default '2000' not null,
  TN_ROU_BET         VARCHAR2(10) default '2000' not null,
  TN_OU_BET          VARCHAR2(10) default '2000' not null,
  TN_M_BET           VARCHAR2(10) default '2000' not null,
  TN_T_BET           VARCHAR2(10) default '2000' not null,
  TN_EO_BET          VARCHAR2(10) default '2000' not null,
  TN_P_BET           VARCHAR2(10) default '2000' not null,
  TN_PR_BET          VARCHAR2(10) default '2000' not null,
  TN_PD_BET          VARCHAR2(10) default '2000' not null,
  TN_F_BET           VARCHAR2(10) default '2000' not null,
  TN_R_SCENE         VARCHAR2(10) default '2000' not null,
  TN_OU_SCENE        VARCHAR2(10) default '2000' not null,
  TN_RE_SCENE        VARCHAR2(10) default '2000' not null,
  TN_ROU_SCENE       VARCHAR2(10) default '2000' not null,
  TN_M_SCENE         VARCHAR2(10) default '2000' not null,
  TN_EO_SCENE        VARCHAR2(10) default '2000' not null,
  TN_T_SCENE         VARCHAR2(10) default '2000' not null,
  TN_PD_SCENE        VARCHAR2(10) default '2000' not null,
  TN_F_SCENE         VARCHAR2(10) default '2000' not null,
  TN_P_SCENE         VARCHAR2(10) default '2000' not null,
  TN_PR_SCENE        VARCHAR2(10) default '2000' not null,
  TN_TURN_R          CHAR(5) default '0' not null,
  TN_TURN_OU         VARCHAR2(5) default '0' not null,
  TN_TURN_RE         VARCHAR2(5) default '0' not null,
  TN_TURN_ROU        VARCHAR2(5) default '0' not null,
  TN_TURN_M          VARCHAR2(5) default '0' not null,
  TN_TURN_T          VARCHAR2(5) default '0' not null,
  TN_TURN_EO         VARCHAR2(5) default '0' not null,
  TN_TURN_PD         VARCHAR2(5) default '0' not null,
  TN_TURN_F          VARCHAR2(5) default '0' not null,
  TN_TURN_P          VARCHAR2(5) default '0' not null,
  TN_TURN_PR         VARCHAR2(5) default '0' not null,
  VB_TURN_R          VARCHAR2(5) default '0' not null,
  VB_TURN_OU         VARCHAR2(5) default '0' not null,
  VB_TURN_ROU        VARCHAR2(5) default '0' not null,
  VB_TURN_RE         VARCHAR2(5) default '0' not null,
  VB_TURN_EO         VARCHAR2(5) default '0' not null,
  VB_TURN_M          VARCHAR2(5) default '0' not null,
  VB_TURN_T          VARCHAR2(5) default '0' not null,
  VB_TURN_PD         VARCHAR2(5) default '0' not null,
  VB_TURN_F          VARCHAR2(5) default '0' not null,
  VB_TURN_PR         VARCHAR2(5) default '0' not null,
  VB_TURN_P          VARCHAR2(5) default '0' not null,
  BK_TURN_R          VARCHAR2(5) default '0' not null,
  BK_TURN_EO         VARCHAR2(5) default '0' not null,
  BK_TURN_OU         VARCHAR2(5) default '0' not null,
  BK_TURN_PR         VARCHAR2(5) default '0' not null,
  BK_R_SCENE         VARCHAR2(10) default '2000' not null,
  BK_EO_SCENE        VARCHAR2(10) default '2000' not null,
  BK_OU_SCENE        VARCHAR2(10) default '2000' not null,
  BK_PR_SCENE        VARCHAR2(10) default '2000' not null,
  BK_R_BET           VARCHAR2(10) default '2000' not null,
  BK_EO_BET          VARCHAR2(10) default '2000' not null,
  BK_OU_BET          VARCHAR2(10) default '2000' not null,
  BK_PR_BET          VARCHAR2(10) default '2000' not null,
  AGENT_RATE         VARCHAR2(5) default '0' not null,
  WORLD_RATE         VARCHAR2(5) default '0' not null,
  AGENT_POINT     VARCHAR2(5) default '0' not null,
  WORLD_POINT     VARCHAR2(5) default '0' not null,
  RATIO              VARCHAR2(10) default '1' not null,
  VB_R_BET           VARCHAR2(10) default '2000' not null,
  VB_RE_BET          VARCHAR2(10) default '2000' not null,
  VB_ROU_BET         VARCHAR2(10) default '2000' not null,
  VB_OU_BET          VARCHAR2(10) default '2000' not null,
  VB_M_BET           VARCHAR2(10) default '2000' not null,
  VB_T_BET           VARCHAR2(10) default '2000' not null,
  VB_EO_BET          VARCHAR2(10) default '2000' not null,
  VB_P_BET           VARCHAR2(10) default '2000' not null,
  VB_PR_BET          VARCHAR2(10) default '2000' not null,
  VB_PD_BET          VARCHAR2(10) default '2000' not null,
  VB_F_BET           VARCHAR2(10) default '2000' not null,
  VB_R_SCENE         VARCHAR2(10) default '2000' not null,
  VB_OU_SCENE        VARCHAR2(10) default '2000' not null,
  VB_RE_SCENE        VARCHAR2(10) default '2000' not null,
  VB_ROU_SCENE       VARCHAR2(10) default '2000' not null,
  VB_M_SCENE         VARCHAR2(10) default '2000' not null,
  VB_EO_SCENE        VARCHAR2(10) default '2000' not null,
  VB_T_SCENE         VARCHAR2(10) default '2000' not null,
  VB_PD_SCENE        VARCHAR2(10) default '2000' not null,
  VB_F_SCENE         VARCHAR2(10) default '2000' not null,
  VB_P_SCENE         VARCHAR2(10) default '2000' not null,
  VB_PR_SCENE        VARCHAR2(10) default '2000' not null,
  FT_HRE_SCENE       VARCHAR2(10) default '2000' not null,
  FT_HRE_BET         VARCHAR2(10) default '2000' not null,
  FS_R_BET           VARCHAR2(6) default '2000' not null,
  FS_R_SCENE         VARCHAR2(6) default '2000' not null,
  FS_TURN_R          CHAR(2) default '5' not null,
  BK_TURN_RE         VARCHAR2(5) default '0' not null,
  BK_TURN_ROU        VARCHAR2(5) default '0' not null,
  BK_RE_SCENE        VARCHAR2(10) default '2000' not null,
  BK_RE_BET          VARCHAR2(10) default '2000' not null,
  BK_ROU_SCENE       VARCHAR2(10) default '2000' not null,
  BK_ROU_BET         VARCHAR2(10) default '2000' not null,
  LASTPAWD           TIMESTAMP(3) default to_timestamp('1900-01-01 00:00:00.00000', 'yyyy-mm-dd hh24:mi:ss:ff'),
  HIDDEN             NUMBER(1) default '0' not null,
  HIDDENSTATUS       NUMBER(4) default '0' not null,
  CANCEL             NUMBER(3) default '0' not null,
  PRETICK            NUMBER(3) default '0' not null,
  TICK               NUMBER(3) default '0' not null,
  FT_PC_BET          NUMBER(8) default '2000' not null,
  FT_PC_SCENE        NUMBER(8) default '2000' not null,
  FT_TURN_PC         NUMBER(3) default '5' not null,
  BS_R_SCENE         NUMBER(11) default '2000',
  BS_R_BET           NUMBER(11) default '2000',
  BS_OU_SCENE        NUMBER(11) default '2000',
  BS_OU_BET          NUMBER(11) default '2000',
  BS_M_SCENE         NUMBER(11) default '2000',
  BS_M_BET           NUMBER(11) default '2000',
  BS_EO_SCENE        NUMBER(11) default '2000',
  BS_EO_BET          NUMBER(11) default '2000',
  BS_T_SCENE         NUMBER(11) default '2000',
  BS_T_BET           NUMBER(11) default '2000',
  BS_P_SCENE         NUMBER(11) default '2000',
  BS_P_BET           NUMBER(11) default '2000',
  BS_PR_SCENE        NUMBER(11) default '2000',
  BS_PR_BET          NUMBER(11) default '2000',
  BS_PC_SCENE        NUMBER(11) default '2000',
  BS_PC_BET          NUMBER(11) default '2000',
  BS_PD_SCENE        NUMBER(11) default '2000',
  BS_PD_BET          NUMBER(11) default '2000',
  BS_TURN_OU         CHAR(5) default '0',
  BS_TURN_M          CHAR(5) default '0',
  BS_RE_SCENE        NUMBER(11) default '2000',
  BS_RE_BET          NUMBER(11) default '2000',
  BS_TURN_RE         CHAR(5) default '0',
  BS_ROU_SCENE       NUMBER(11) default '2000',
  BS_ROU_BET         NUMBER(11) default '2000',
  BS_TURN_ROU        CHAR(5) default '0',
  BS_TURN_EO         CHAR(5) default '0',
  BS_TURN_P          CHAR(5) default '0',
  BS_TURN_PR         CHAR(5) default '0',
  BS_TURN_PC         CHAR(5) default '0',
  BS_TURN_PD         CHAR(5) default '0',
  BS_TURN_T          CHAR(5) default '0',
  BS_TURN_R          CHAR(5) default '',
  FT_RM_BET          CHAR(20) default '2000' not null,
  FT_RM_SCENE        CHAR(20) default '2000' not null,
  FT_TURN_RM         CHAR(5) default '0' not null,
  OP_R_BET           NUMBER(11) default '2000' not null,
  OP_RE_BET          NUMBER(11) default '2000' not null,
  OP_ROU_BET         NUMBER(11) default '2000' not null,
  OP_OU_BET          NUMBER(11) default '2000' not null,
  OP_M_BET           NUMBER(11) default '2000' not null,
  OP_T_BET           NUMBER(11) default '2000' not null,
  OP_EO_BET          NUMBER(11) default '2000' not null,
  OP_P_BET           NUMBER(11) default '2000' not null,
  OP_PR_BET          NUMBER(11) default '2000' not null,
  OP_PD_BET          NUMBER(11) default '2000' not null,
  OP_F_BET           NUMBER(11) default '2000' not null,
  OP_R_SCENE         NUMBER(11) default '2000' not null,
  OP_OU_SCENE        NUMBER(11) default '2000' not null,
  OP_RE_SCENE        NUMBER(11) default '2000' not null,
  OP_ROU_SCENE       NUMBER(11) default '2000' not null,
  OP_M_SCENE         NUMBER(11) default '2000' not null,
  OP_EO_SCENE        NUMBER(11) default '2000' not null,
  OP_T_SCENE         NUMBER(11) default '2000' not null,
  OP_PD_SCENE        NUMBER(11) default '2000' not null,
  OP_F_SCENE         NUMBER(11) default '2000' not null,
  OP_P_SCENE         NUMBER(11) default '2000' not null,
  OP_PR_SCENE        NUMBER(11) default '2000' not null,
  OP_TURN_R          CHAR(5) default '0' not null,
  OP_TURN_OU         CHAR(5) default '0' not null,
  OP_TURN_RE         CHAR(5) default '0' not null,
  OP_TURN_ROU        CHAR(5) default '0' not null,
  OP_TURN_M          CHAR(5) default '0' not null,
  OP_TURN_T          CHAR(5) default '0' not null,
  OP_TURN_EO         CHAR(5) default '0' not null,
  OP_TURN_PD         CHAR(5) default '0' not null,
  OP_TURN_F          CHAR(5) default '0' not null,
  OP_TURN_P          CHAR(5) default '0' not null,
  OP_TURN_PR         CHAR(5) default '0' not null,
  TN_PC_SCENE        NUMBER(11) default '5000' not null,
  TN_PC_BET          NUMBER(11) default '250000' not null,
  TN_TURN_PC         CHAR(5) default '0' not null,
  VB_PC_SCENE        NUMBER(11) default '5000' not null,
  VB_PC_BET          NUMBER(11) default '250000' not null,
  VB_TURN_PC         CHAR(5) default '0' not null,
  BK_PC_SCENE        NUMBER(11) default '5000' not null,
  BK_PC_BET          NUMBER(11) default '250000' not null,
  BK_TURN_PC         CHAR(5) default '0' not null,
  OP_PC_SCENE        NUMBER(11) default '5000' not null,
  OP_PC_BET          NUMBER(11) default '250000' not null,
  OP_TURN_PC         CHAR(5) default '0' not null,
  M                  NUMBER(11) default '0' not null,
  R                  NUMBER(11) default '0' not null,
  OU                 NUMBER(11) default '0' not null,
  PD                 NUMBER(11) default '0' not null,
  T                  NUMBER(11) default '0' not null,
  F                  NUMBER(11) default '0' not null,
  P                  NUMBER(11) default '0' not null,
  FS                 NUMBER(11) default '0' not null,
  MAX                NUMBER(11) default '0' not null,
  ISONLINE           NUMBER(1) default '0' not null,
  ONLINETIME         TIMESTAMP(3) default to_timestamp('1900-01-01 00:00:00.00000', 'yyyy-mm-dd hh24:mi:ss:ff'),
  NOTES              VARCHAR2(50),
  ADDRESS            VARCHAR2(100),
  ADMIN              VARCHAR2(10)
);
alter table WEB_MEMBER add constraint WEB_MEMBER_Oid unique (Oid);
alter table WEB_MEMBER add constraint WEB_MEMBER_Memname unique (Memname);
alter table WEB_MEMBER add constraint WEB_MEMBER_Active unique (Active);
alter table WEB_MEMBER add constraint WEB_MEMBER_LogDate unique (LogDate);
alter table WEB_MEMBER add constraint WEB_MEMBER_Agents unique (Agents);
alter table WEB_MEMBER add constraint WEB_MEMBER_world unique (world);
alter table WEB_MEMBER add constraint WEB_MEMBER_corprator unique (corprator);
alter table WEB_MEMBER add constraint WEB_MEMBER_super unique (super);
alter table WEB_MEMBER add constraint WEB_MEMBER_Status unique (Status);
alter table WEB_MEMBER add constraint WEB_MEMBER_pay_type unique (pay_type);
alter table WEB_MEMBER add constraint WEB_MEMBER_lastpawd unique (lastpawd);
alter table WEB_MEMBER add constraint WEB_MEMBER_AddDate unique (AddDate);
alter table WEB_MEMBER add constraint WEB_MEMBER_tick unique (tick);


