/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-01-24 04:37:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import com.tbb.forum.*;

public final class message_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String sessionUsername = (String)session.getAttribute("username"); 
      out.write('\r');
      out.write('\n');
 String sessionPassword = (String)session.getAttribute("password"); 
      out.write('\r');
      out.write('\n');
 String sessionType = (String)session.getAttribute("type"); 
      out.write("\r\n");
      out.write("\r\n");
 String forum_id = request.getParameter("forum_id"); 
      out.write('\r');
      out.write('\n');
 String reqThread_id = request.getParameter("thread_id"); 
      out.write('\r');
      out.write('\n');
 String start = request.getParameter("start"); 
      out.write("\r\n");
      out.write("      \t\t\t\t\r\n");
 Utilities.addView(forum_id,reqThread_id); 
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Read Message", request.getCharacterEncoding()), out, true);
      out.write("\t \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/body.jsp", out, true);
      out.write('\r');
      out.write('\n');
 if( sessionUsername != null){
      out.write("\r\n");
      out.write("\t<table width=\"100%\" height=\"20\" border=\"0\" cellpadding=\"1\" cellspacing=\"1\">\r\n");
      out.write("\t\t<tr> \r\n");
      out.write("\t\t\t<td height=\"20\" valign=\"top\" class=\"pathBar\">\r\n");
      out.write("\t\t\t\t<a href=\"index.jsp\" class=\"pathBarLink\">");
      out.print( Variable.getForumName() );
      out.write("</a><span class=\"pathBarSeperator\"> > </span>\r\n");
      out.write("\t\t\t\t<a href=\"./index.jsp?page=thread&forum_id=");
      out.print( forum_id );
      out.write("\" class=\"pathBarLink\">");
      out.print( Utilities.getforumTile(forum_id) );
      out.write("</a><span class=\"pathBarSeperator\"> > </span>\r\n");
      out.write("\t\t\t\t<a href=\"./index.jsp?page=thread&forum_id=");
      out.print( forum_id );
      out.write("&thread_id=");
      out.print(reqThread_id);
      out.write("&start=");
      out.print( start );
      out.write("\" class=\"pathBarLink\">");
      out.print( Utilities.getThreadTile(forum_id,reqThread_id) );
      out.write("</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<TD align=\"right\" class=\"pathBar\">\r\n");
      out.write("\t\t\t\t");
      out.print( Utilities.getMorePages(Utilities.getReplies(forum_id,reqThread_id),forum_id,reqThread_id,false) );
      out.write("\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_start.jsp", out, true);
      out.write("                   \r\n");
      out.write("\r\n");
      out.write("\t");
					
	DBConnectie db = new DBConnectie(Variable.getDb(),Variable.getDbLogin(),Variable.getDbPassword());

	db.connect();
						
	String thread_id = "null";
	String lastReply_id = "null";

	ResultSet rs = db.selectQuery(
		"SELECT * FROM forum_message " +
		"WHERE forum_id=\"" + forum_id + "\" AND thread_id =\"" + reqThread_id + "\" ORDER BY reply_id LIMIT "+ start + "," + Variable.getMessagePerPage());
							
		while(rs.next()){
			thread_id = rs.getString("thread_id");
			String reply_id = rs.getString("reply_id");
			String message = rs.getString("message");
			String user = rs.getString("user");
			String date_time = rs.getString("date_time");
	
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_start_title.jsp", out, true);
      out.write('\r');
      out.write('\n');
      out.write('	');
 String titleAdmin = "Posted On: " + date_time + "&nbsp;&nbsp;&nbsp;<a href=\"./index.jsp?page=editmessage&forum_id=" + forum_id + "&thread_id=" + thread_id + "&reply_id=" + reply_id + "&start=" + start + "\">Edit</a>&nbsp;&nbsp;&nbsp;<a href=\"servlet/forum.DeleteReply?forum_id=" + forum_id + "&thread_id=" + thread_id + "&reply_id=" + reply_id + "&start=" + start + "\">Delete</a>"; 
      out.write('\r');
      out.write('\n');
      out.write('	');
 String titleUser = "Posted On: " + date_time + "&nbsp;&nbsp;&nbsp;<a href=\"./index.jsp?page=editmessage&forum_id=" + forum_id + "&thread_id=" + thread_id + "&reply_id=" + reply_id + "&start=" + start + "\">Edit</a>"; 
      out.write('\r');
      out.write('\n');
      out.write('	');
 String titleOther = "Posted On: " + date_time; 
      out.write('\r');
      out.write('\n');
      out.write('	');
 if(sessionType.equals("Admin")){ 
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_title.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( titleAdmin ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("colspan", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("2", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("align", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("middle", request.getCharacterEncoding()), out, true);
      out.write('\r');
      out.write('\n');
      out.write('	');
 }else{ 
      out.write("\r\n");
      out.write("\t\t");
 if(sessionUsername.equals(user)){ 
      out.write("\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_title.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( titleUser ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("colspan", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("2", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("align", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("middle", request.getCharacterEncoding()), out, true);
      out.write("\r\n");
      out.write("\t\t");
 }else{ 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_title.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( titleOther ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("colspan", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("2", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("align", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("middle", request.getCharacterEncoding()), out, true);
      out.write("\t\t\t        \r\n");
      out.write("\t\t");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
 } 
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_start_body.jsp", out, true);
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t");
    	
								
		ResultSet rs2 = db.selectQuery(
			"SELECT * FROM forum_users WHERE user_name =\"" + user + "\"");
			
		String group = null;
		String avatar = null;
		String member_title = null;
		String signature = null;	
		while(rs2.next()){
			group = rs2.getString("type");
			avatar = rs2.getString("avatar");
			member_title = rs2.getString("member_title");
			signature = rs2.getString("signature");
		}
						
		ResultSet rs3 = db.selectQuery(
			"SELECT count(*) count FROM forum_message WHERE user =\"" + user + "\"");
		
		while(rs3.next()){
			String messageCount = rs3.getString("count");
									
			if(avatar == null){
				avatar = "<br>";
			}else{
				avatar = "<img src=\"" + avatar + "\" width=\"65\" height=\"65\"><br>";								
			}						
			if(member_title == null){
				member_title = "";
			}else{
				member_title = member_title + "<br>";
			}						
			if(signature == null){
				signature = "";
			}else{
				signature =	"<br><br>--------<br>" + signature;
			}
	
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_body.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("width", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("100", request.getCharacterEncoding()), out, true);
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<b>");
      out.print( user.toUpperCase() );
      out.write("</b>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t");
      out.print( member_title );
      out.write("\r\n");
      out.write("\t\t\t");
      out.print( avatar );
      out.write("<br>\r\n");
      out.write("\t\t\tGroup: ");
      out.print( group );
      out.write("<br>\r\n");
      out.write("\t\t\tPosts: ");
      out.print( messageCount );
      out.write("<br>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_body.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("width", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("400", request.getCharacterEncoding()), out, true);
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.print( message );
      out.print( signature );
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_close_body.jsp", out, true);
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t");
 lastReply_id = reply_id; 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
 db.close(); 
      out.write("\t\t\t\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_start_title.jsp", out, true);
      out.write(" \r\n");
      out.write("\t");
 String back = "<a href=\"./index.jsp?page=thread&forum_id=" + forum_id + "\">Back</a> " + Utilities.getMorePages(Utilities.getReplies(forum_id,thread_id),forum_id,thread_id,false); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_title.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( back ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("colspan", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("2", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("align", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("left", request.getCharacterEncoding()), out, true);
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_close.jsp", out, true);
      out.write(" \r\n");
      out.write("\t<br>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_start.jsp", out, true);
      out.write(" \r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_title.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Add Reply", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("colspan", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("3", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("align", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("left", request.getCharacterEncoding()), out, true);
      out.write("\t\t\t\t\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_start_body.jsp", out, true);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_body.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("width", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("200", request.getCharacterEncoding()), out, true);
      out.write(" \t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"servlet/forum.AddReply\" method=\"POST\" name=\"formmessage\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"forum_id\" value=\"");
      out.print( forum_id );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"thread_id\" value=\"");
      out.print( thread_id );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"lastReply_id\" value=\"");
      out.print( lastReply_id );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"user\" value=\"");
      out.print( sessionUsername );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"start\" value=\"");
      out.print( start );
      out.write("\">\r\n");
      out.write("\tReply:\r\n");
      out.write("\t<textarea name=\"message\" cols=\"45\" rows=\"10\" maxlength=3000></textarea>\r\n");
      out.write("\t<input type=\"submit\" value=\"submit\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_body.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("width", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("200", request.getCharacterEncoding()), out, true);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/textStyle.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_body.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("width", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("200", request.getCharacterEncoding()), out, true);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/emoticons.jsp", out, true);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_close_body.jsp", out, true);
      out.write("\t\t\t\t \r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_close.jsp", out, true);
      out.write("        \r\n");
      out.write("        \t\t\r\n");
      out.write("              \r\n");
 }else { 
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_start.jsp", out, true);
      out.write(" \r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_title.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Error", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("colspan", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("1", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("align", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("left", request.getCharacterEncoding()), out, true);
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_start_body.jsp", out, true);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_body.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("width", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("200", request.getCharacterEncoding()), out, true);
      out.write("\r\n");
      out.write("\tYou have to login first !\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<a href=\"./register.jsp\">Register</a>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_close_body.jsp", out, true);
      out.write("\t\t\t\t \r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/table_close.jsp", out, true);
      out.write('\r');
      out.write('\n');
 } 
      out.write("   \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/footer.jsp", out, true);
      out.write("  \r\n");
      out.write("         \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
